# -*- coding: utf-8 -*-
"""Day1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eG0M9SG1fe2NjE0s9dBwJeED7wBtv-_u
"""

""" Question 1 
Write a Python program to print all Prime numbers in an Interval."""

lower = int(input("Enter lower value:"))
upper = int(input("Enter upper value:"))
for a in range(lower,upper+1):
  if a > 1:
    for i in range(2,a):
      if (a % i == 0 ):
        break
    else:
        print(a)

""" 
Question 2
Write a Python Program for factorial of a number."""

num = int(input("Enter a number"))
if (num >=0):
  factorial = 1
  for i in range(1,num+1):
    factorial = factorial * i
  print("The factorial of a given number",num," is ",factorial)
else :
  print("sorry factorial number is not exits for negative numbers")

"""Question 3
Find the sum of n numbers by using the while loop"""

n = int(input("Enter a number"))
if n < 0:
   print("Enter a positive number")
else:
   sum = 0
   while (n > 0):
       sum += n
       n -= 1
print("The sum of n natural numbers is :",sum)